### ISSUE TITLE
css, img static 처리

### ISSUE THREAD

**Issue by rindingdong** [Jungmin-Hong/Likelion10_SummerHackathon#13]
- [x] #7 영수증 화면 모아보는 화면
- [x] #8 영수증 글 작성
- [x] #9 03_일반/상세 정보 수정 화면
- [x] #10 05_마이페이지 화면
- [x] #11 06_영수증 파티 모아보는 화면
- [x] #15 홈화면
- [x] #24 
- [x] #27 
- [x] #28 
- [x] #29
- [x] #30
- [x] #31
- [x] #37 
- [x] #38
